### ISSUE TITLE
hard to use generateFigSpec because of private functions

### ISSUE THREAD

**Issue by developer-guy** [withfig/autocomplete-tools#32]
Hello, I wanted to talk about a problem that I have while adding opa CLI autocompletion support to fig over cobra packages. There is a method called toTypescript() which is a private method defined for Spec struct, IMO, we should make it public because there is another method named MakeFigSpec that I can use to generate spec struct that is already public. So, when we make toTypescript() public, we'll be able to store the output wherever I want, in the current design, the only option I have is stdout which causes trouble while copying and pasting it to a file. 

The implementation will be looking like the following:

```shell
s := genFigSpec.MakeFigSpec(root).ToTypescript()
```

**Comment by developer-guy** [comment]
feel free to assign it to me please, I'm willing to work on it if you agree.

**Comment by fedeci** [comment]
It makes sense, thanks for doing it!
