### ISSUE TITLE
`no-useless-insertvalue` ignores newline char

### ISSUE THREAD

**Issue by LomaxOnTheRun** [withfig/autocomplete-tools#71]
It looks like the `no-useless-insertvalue` gets triggered even if the `insertValue` has an additional newline character at the end of the name. Adding a newline character changes the functionality of the subcommand as omitting the `insertValue` means that to autocomplete and then run the command you need to hit enter twice, instead of just once.

```typescript
const completionSpec: Fig.Spec = {
  name: "mySpec",
  subcommands: [
    {
      name: "doThing",
      insertValue: "doThing\n", // This will trigger the exception
    },
  ],
}
```

I'm using VS Code version 1.69.2 (Universal).

**Comment by fedeci** [comment]
Just released a fix!
